services:
  - type: web

    name: incident-ai-backend

    env: python

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn mcp_servers.log_server:app --host 0.0.0.0 --port $PORT

    envVars:

      - key: GROQ_API_KEY
        sync: false

      - key: LANGCHAIN_API_KEY
        sync: false

      - key: LANGCHAIN_TRACING_V2
        value: "true"

      - key: LANGCHAIN_PROJECT
        value: incident-ai